### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by marek-stoj** [babakks/vscode-open-with-vim#1]
When trying to open a file using Nano I get the following error:

![image](https://user-images.githubusercontent.com/194082/195770398-1f4b5560-c629-43d5-b5ca-1928c4ea7c99.png)

Any help with this?

**Comment by babakks** [comment]
@marek-stoj Thanks for the feedback!

That's because I couldn't test the extension on Windows. I've just updated it to support PowerShell syntax. Could you please upgrade to `v0.0.3` and check if things are working? Note that you had to install Vi/Vim/Nano beforehand.

**Comment by babakks** [comment]
@marek-stoj Any updates on this?

**Comment by marek-stoj** [comment]
I've tested the new version. There is still an issue on Windows but I know
how to fix it. I will create a PR tomorrow.

**Comment by babakks** [comment]
Just published the new version 0.0.4. A few minutes from now it'll be accessible for the upgrade through the extensions sidebar.
